### ISSUE TITLE
How to install openai in PyMOL

### ISSUE THREAD

**Issue by shiokoo** [ChatMol/ChatMol#37]
When I enter the command line"pip install openai" following your README.md, I get the SyntaxError shown in the following picture. Sorry, I don't know what to do next.
<img width="624" alt="image" src="https://github.com/ChatMol/ChatMol/assets/65479541/6ba042aa-5cbd-4112-b71c-475a0f6b786c">

**Comment by JinyuanSun** [comment]
If you started PyMOL by clicking the PyMOL icon, the installation in the PyMOL cmd should work. If you started the PyMOL session from the command line, this behavior is normal. I am still investigating the reason for this issue.

If you installed PyMOL using Conda, you can install the openai package directly in your terminal after activating the Conda environment used for PyMOL.

**Comment by shiokoo** [comment]
Yeah, thanks for your help.😊
