### ISSUE TITLE
Incorrect API Key provided

### ISSUE THREAD

**Issue by GalBStarget** [ChatMol/ChatMol#39]
Hi,

I am trying to use ChatMOL as a streamlit app page.

While trying to prompt the api with 
`response = chatmol.chat_with_gpt(user_input)`

I get `Error: Error code: 401 - {'error': {'message': 'Incorrect API key provided: True. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

Also, when I try to use chatlite, with `chatmol.chatlite(prompt)`, 
I get: 
`Failed to query server: 500 - <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.`

Note that I've made sure the OpenAI key is passed properly from .env file and set properly with `.set_api_key` method. I've also checked that the `apikey.json` that is created, holds the correct key and value.

Thanks.

**Comment by JinyuanSun** [comment]
Thank you for letting use know. I'v fixed the chatlite server.
As for the issue regards to the API_KEY, you can set the key by adding it to the `~/.bashrc`.

**Comment by GalBStarget** [comment]
Can you please elaborate? I am using MacOS if it's relevant.

**Comment by JinyuanSun** [comment]
1. Open Terminal on your Mac.

2. Open your .bashrc file using a text editor:
   ```
   nano ~/.bashrc
   ```

3. Add this line to the file, replacing YOUR_API_KEY with your actual key:
   ```
   export API_KEY="YOUR_API_KEY"
   ```

4. Save and exit:
   - If using nano, press Ctrl+X, then Y, then Enter.

5. Reload your .bashrc file:
   ```
   source ~/.bashrc
   ```

6. Check if it worked:
   ```
   echo $API_KEY
   ```

This should print your API key.

**Comment by GalBStarget** [comment]
Thanks! It worked.
For further development: what's the best and most stable way to store the API over production env?
